name: signLanguage
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyter
  - ipykernel
  - scikit-learn
  - pandas
  - pip:
      - streamlit
      - opencv-python
      - mediapipe
      - numpy
      - google-generativeai
      - gtts
      - langchain-google-genai
      - python-dotenv
      - langchain